[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tts_example"
path = "tts_example.rs"


[dependencies]
client = { path = "../client" }
plugins = { path = "../plugins" }
env_logger = "0.11.8"
log = "0.4"
